#ifndef PARAMS_H
#define PARAMS_H

#define CHUNK_SIZE 6000
#define TIME_CHUNK_SZ 10000
#define TIME_OFFSET 550
#define NUM_OVERLAP 2.5

/*TODO DETERMINE OPTIMAL PARAMS FOR PITCH SHIFTING*/
#define BUFFER_LEN 512
#endif